Repository NicoleLatifi/refactor-tractor, pull requests merged in 2020-07, with the labels that each got.

#28 Repo setup/abd pr template
  package-lock.json
  package.json
  pull_request_template.md
Labels: documentation, github workflow

#34 Add comments with functional info, invocation, and refactoring opportunities
  src/Activity.js
  src/User.js
Labels: exploration, planning, research

#35 Research/nw continue investigate qs
  src/index.html
  src/scripts.js
Labels: exploration, planning, research

#44 Reafactor/abd scss variables
  src/css/_base.scss
  src/css/_buttons.scss
  src/css/_changing-classes.scss
  src/css/_header.scss
  src/css/_main.scss
  src/css/_text-elements.scss
  src/css/_variables.scss
  src/css/base.scss
  src/css/styles.scss
  src/scripts.js
Labels: css, organize, refactor

#51 Feature/abd fetch data explore
  src/Activity.js
  src/css/styles.scss
  src/scripts.js
Labels: bug, enhancement, exploration

#61 Data/abd implement fetch
  src/User.js
  src/scripts.js
Labels: bug, enhancement, refactor

#64 Data/nw implement fetch
  src/scripts.js
Labels: bug, enhancement, help wanted, refactor

#65 Data/abd fix fetch
  src/Activity.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
Labels: bug, fetch

#67 Refactor/nw for loops
  src/Activity.js
  src/DomUpdates.js
  src/User.js
  src/UserRepository.js
Labels: refactor

#68 Feature/nw readme
  README.md
Labels: documentation

#72 Feature/nw readme cont
  README.md
Labels: documentation, enhancement
